name: report
version: 0.1.0.0
synopsis: Functional Programming project report
description: See report.pdf
maintainer: Flip Lijnzaad <flip.lijnzaad@student.uva.nl>
category: Logic

ghc-options: -Wall

dependencies:
  - base >= 4.14 && < 5

library:
  source-dirs: lib

tests:
  tests:
    main: tests.lhs
    source-dirs: test
    dependencies:
      - report
      - hspec
